# Generated by Django 3.0.6 on 2020-05-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200520_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='job_description',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='post',
            name='skills',
            field=models.TextField(max_length=3000),
        ),
    ]
