# Generated by Django 3.0.5 on 2020-05-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'Selected'), ('0', 'Rejected')], max_length=10, null=True),
        ),
    ]
