# Generated by Django 3.0.5 on 2020-05-04 06:09

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200503_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='contact',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
