# Generated by Django 3.0.5 on 2020-05-04 07:18

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200504_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='category',
            field=models.CharField(blank=True, choices=[('Selected', 'Selected'), ('Rejected', 'Rejected')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='contact',
            field=phone_field.models.PhoneField(blank=True, help_text='Start with country code', max_length=31),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date_of_interview',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='degree_score',
            field=models.IntegerField(choices=[(60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99)]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='hr_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
