# Generated by Django 3.0 on 2020-03-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20170603_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('optiona', models.CharField(max_length=100)),
                ('optionb', models.CharField(max_length=100)),
                ('optionc', models.CharField(max_length=100)),
                ('optiond', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('catagory', models.CharField(choices=[('aptitude', 'Aptitude'), ('verbal ability', 'Verbal Ability'), ('maths', 'Maths'), ('generalknowledge', 'GeneralKnowledge')], max_length=20)),
            ],
            options={
                'ordering': ('-catagory',),
            },
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
