# Generated by Django 3.0.5 on 2020-04-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200331_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='catagory',
            field=models.CharField(choices=[('aptitude', 'Aptitude'), ('verbalability', 'Verbal Ability'), ('maths', 'Maths'), ('generalknowledge', 'GeneralKnowledge')], max_length=20),
        ),
    ]
