# Generated by Django 3.0.5 on 2020-04-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200415_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='catagory',
            field=models.CharField(choices=[('aptitude', 'Quantitative Aptitude'), ('verbalability', 'Verbal Ability'), ('maths', 'Maths'), ('generalknowledge', 'General Knowledge')], max_length=20),
        ),
    ]
